version: '3'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: localhost
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: 20012002
      POSTGRES_USER: ed
      POSTGRES_DB: auth_up
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

    volumes: 
      pgdata:
